import {describe, it, expect} from 'vitest';
import {ATOMIC_GLOBAL, ARC_GLOBAL, ARC_GLOBAL_OBSERVER} from '../../../../../lib/modules/JSX/script/atomic';

describe('Modules - JSX - script - atomic', () => {
    describe('ATOMIC_GLOBAL', () => {
        it('Should be minified correct', () => {
            expect(ATOMIC_GLOBAL).toBe(
                [
                    '(function(){',
                    'const def=(n,v,t=window)=>{',
                    'if(!t[n])Object.defineProperty(t,n,{value:v,configurable:!1,writable:!1});',
                    '};',
                    /* Equality */
                    'const eq=(a,b)=>{',
                    'if(a===b)return !0;',
                    'switch(typeof a){',
                    'case"number":return Number.isNaN(a)&&Number.isNaN(b);',
                    'case"object":{',
                    'if(!a||!b)return !1;',
                    'if(Array.isArray(a))return Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>eq(v,b[i]));',
                    'const pa=Object.prototype.toString.call(a);',
                    'const pb=Object.prototype.toString.call(b);',
                    'if(pa!==pb)return !1;',
                    'switch(pa){',
                    'case"[object Date]":return a.valueOf()===b.valueOf();',
                    'case"[object Object]":{',
                    'const ka=Object.keys(a);',
                    'const kb=Object.keys(b);',
                    'if(ka.length!==kb.length)return !1;',
                    'return ka.every(k=>eq(a[k],b[k]));',
                    '}',
                    'case"[object Error]":return a.name===b.name&&a.message===b.message;',
                    'case"[object RegExp]":return String(a)===String(b);',
                    'default:return !1;',
                    '}}',
                    'default:return !1;',
                    '}};',
                    'def("$tfequal",eq);',
                    /* clone */
                    'def("$tfclone",v=>(v===undefined||v===null||typeof v!=="object")?v:structuredClone(v));',
                    /* event creation */
                    'def("$tfevent",(t,o)=>{',
                    'try{return new CustomEvent(t,o);}',
                    'catch(_){const e=document.createEvent("CustomEvent");e.initCustomEvent(t,o?.bubbles,o?.cancelable,o?.detail);return e;}',
                    '});',
                    /* Relay */
                    'def("$tfr",(()=>{',
                    'const s=Object.create(null);',
                    'return Object.freeze({',
                    'publish:(msg,data)=>{if(typeof msg!=="string"||!s[msg])return;for(let i=0;i<s[msg].length;i++)try{s[msg][i].fn(data)}catch{}},',
                    'subscribe:(vmid,msg,fn)=>{if(typeof vmid!=="string"||typeof msg!=="string"||typeof fn!=="function")return;const subs=(s[msg]??=[]);const idx=subs.findIndex(el=>el.id===vmid);if(idx>=0)subs[idx].fn=fn;else subs.push({id:vmid,fn});},',
                    'unsubscribe:(vmid,msg)=>{if(typeof vmid!=="string")return;if(typeof msg==="string"){if(!(msg in s))return;s[msg]=s[msg].filter(el=>el.id!==vmid);}else{for(const key of Object.keys(s)){s[key]=s[key].filter(el=>el.id!==vmid);}',
                    '}}})})());',
                    /* Observer */
                    'def("$tfo",(()=>{',
                    'const clean=nR=>{',
                    'if(nR.$tfVM){',
                    'if(typeof nR.$unmount==="function"){try{nR.$unmount()}catch{}}',
                    'window.$tfr?.unsubscribe(nR.$uid);',
                    'window.$tfc?.delete(nR.$uid);',
                    'window.$tfarc?.release(nR.$uid);',
                    '}',
                    'if(nR.children?.length){',
                    'for(let i=0;i<nR.children.length;i++){',
                    'clean(nR.children[i]);',
                    '}',
                    '}',
                    '};',
                    'const o=new MutationObserver(e=>{',
                    'for(let i=0;i<e.length;i++){',
                    'for(let y=0;y<e[i].removedNodes.length;y++){',
                    'clean(e[i].removedNodes[y]);',
                    '}',
                    '}',
                    '});',
                    'o.observe(document.body,{childList:!0,subtree:!0});',
                    'return o;',
                    '})());',
                    /* Store */
                    'def("$tfs",(()=>{',
                    'const s=Object.create(null);',
                    'return Object.freeze({',
                    'get:key=>{if(typeof key!=="string"||!key)return undefined;return s[key]},',
                    'set:(key,val)=>{',
                    'if(typeof key!=="string"||!key)return;',
                    's[key]=val;',
                    'window.$tfr.publish("$store:"+key,val);',
                    '},',
                    '});})());',
                    /* Global clock map */
                    'def("$tfc",new Map());',
                    /* Global clock ticker */
                    'def("$tfcr",(()=>{',
                    'let tp=false;',
                    'const tv=new Set();',
                    'return uid=>{tv.add(uid);if(!tp){tp=true;requestAnimationFrame(()=>{const uids=[...tv.values()];tp=false;tv.clear();for(let i=0;i<uids.length;i++){try{const fn=window.$tfc.get(uids[i]);if(fn)fn();}catch{}}});}};',
                    '})());',
                    /* Global data reactor */
                    'def("$tfdr",(root,raw)=>{',
                    'const store=structuredClone(raw);',
                    'const subs=Object.create(null);',
                    'const pending=new Set();',
                    'const get=path=>path.split(".").reduce((o,k)=>o?.[k],store);',
                    'const set=(path,val)=>{const k=path.split(".");let c=store;for(let i=0;i<k.length-1;i++)c=c[k[i]]??={};const last=k.at(-1);if(c[last]===val)return;c[last]=val;};',
                    'const notify=path=>{let c="";const parts=path.split(".");for(let i=0;i<parts.length;i++){c=i===0?parts[0]:c+"."+parts[i];pending.add(c);}window.$tfcr(root.$uid);};',
                    'const tick=()=>{if(!pending.size)return;for(const key of pending){const handlers=subs[key];if(!handlers)continue;const val=get(key);for(let i=0;i<handlers.length;i++){try{const fn=handlers[i];if(!window.$tfequal(fn._last,val)){fn(val);fn._last=window.$tfclone(val);}}catch{}}}pending.clear();};',
                    'const patch=(obj,val)=>{const marks=new Set();if(typeof obj==="string"){set(obj,val);marks.add(obj);}else{const walk=(path,cursor)=>{for(const k in cursor){const full=path?path+"."+k:k;const v=cursor[k];if(Object.prototype.toString.call(v)==="[object Object]")walk(full,v);else{set(full,v);marks.add(full);}}};walk("",obj);}for(const path of marks)notify(path);};',
                    'const getIV=(els,path)=>{if(!els.length)return undefined;const el=els[0];if(el.type==="checkbox"){if(els.length>1)return [...els].filter(e=>e.checked).map(e=>e.value);return !!el.checked;}if(el.type==="radio"){const c=[...els].find(e=>e.checked);return c?c.value:get(path);}if(el.tagName==="SELECT"&&el.multiple)return [...el.selectedOptions].map(o=>o.value);return el.value;};',
                    'const setIV=(els,val)=>{if(!els.length)return;const e=els[0];if(els.length>1&&e.type==="checkbox"){for(const el of els)el.checked=Array.isArray(val)&&val.includes(el.value);}else if(e.type==="checkbox")e.checked=!!val;else if(e.type==="radio")e.checked=e.value===val;else if(e.tagName==="SELECT"&&e.multiple&&Array.isArray(val)){for(const o of e.options)o.selected=val.includes(o.value);}else e.value=val??"";};',
                    'window.$tfc.set(root.$uid,tick);',
                    'return new Proxy(store,{',
                    'get(_,key){switch(key){',
                    'case"$bind":return (path,selector,watcher)=>{const els=[...root.querySelectorAll(selector)];if(!els.length)return;const c=get(path);if(c===undefined){set(path,getIV(els,path));notify(path);}else{setIV(els,c);}const fn=()=>{set(path,getIV(els,path));notify(path);};for(const el of els){el.addEventListener("input",fn);if(el.type==="checkbox"||el.type==="radio"||el.tagName==="SELECT")el.addEventListener("change",fn);}(subs[path]??=[]).push(v=>setIV(els,v));if(typeof watcher==="function"){watcher._last=window.$tfclone(get(path));subs[path].push(watcher);}else if(typeof watcher?.handler==="function"){const{immediate,handler}=watcher;handler._last=window.$tfclone(get(path));subs[path].push(handler);if(immediate===true)handler(handler._last);}};',
                    'case"$watch":return (path,fn,opts={})=>{if(typeof path!=="string"||typeof fn!=="function")return;(subs[path]??=[]).push(fn);fn._last=window.$tfclone(get(path));if(opts?.immediate===true)fn(fn._last);};',
                    'case"$set":return patch;',
                    'default:return store[key];',
                    '}},',
                    'set(_,key,val){if(window.$tfequal(store[key],val))return true;store[key]=val;notify(String(key));return true;}',
                    '});});',
                    /* Utils */
                    'def("$tfutils",(()=>{const obj=Object.create(null);const oD=(n,v)=>def(n,v,obj);',
                    'oD("clear",n=>{while(n.firstChild)n.removeChild(n.firstChild);});',
                    'oD("debounce",(fn,ms)=>{let t;return (...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms);};});',
                    'oD("eq",window.$tfequal);',
                    'oD("uid",()=>crypto?.randomUUID?.()??Math.random().toString(36).slice(2));',
                    'oD("sleep",ms=>new Promise(r=>setTimeout(r,ms)));',
                    'oD("fetch",async(url,o={})=>{const{method="GET",headers={},body,timeout,credentials="include"}=o;const isJSON=body&&typeof body==="object"&&!(body instanceof FormData);const nHeaders={...headers};const payload=isJSON?JSON.stringify(body):body;if(isJSON&&!("Content-Type"in nHeaders))nHeaders["Content-Type"]="application/json";const ctrl=typeof timeout==="number"?new AbortController():null;const tId=ctrl?setTimeout(()=>ctrl.abort(),timeout):null;try{const r=await fetch(url,{method,headers:nHeaders,body:method!=="GET"&&body!==undefined?payload:undefined,signal:ctrl?.signal,credentials});if(tId)clearTimeout(tId);const rt=r.headers.get("Content-Type")?.toLowerCase()||"";let c;try{if(rt.includes("application/json"))c=await r.json();else if(rt.includes("text/html")){const v=await r.text();c=document.createRange().createContextualFragment(v);}else if(rt.includes("text/"))c=await r.text();else if(rt.includes("application/octet-stream"))c=await r.blob();else c=await r.text();}catch{}return {content:c??null,ok:r.status>=200&&r.status<300,status:r.status,headers:r.headers,raw:r};}catch(err){if(tId)clearTimeout(tId);if(err?.name==="AbortError"){return {content:null,ok:false,status:408,headers:new Headers(),raw:null};}throw err;}});',
                    'oD("fire",(n,t,o)=>n.dispatchEvent(window.$tfevent(t,{detail:o?.data,bubbles:(o?.mode??"up")==="up",cancelable:!0})));',
                    'oD("on",(n,t,fn)=>{n.addEventListener(t,fn);return ()=>n?.removeEventListener(t,fn);});',
                    'oD("once",(n,t,fn)=>{const w=e=>{try{fn(e);}finally{n?.removeEventListener(t,w);}};n.addEventListener(t,w);});',
                    'oD("query",(n,q)=>{if(!n?.querySelector||typeof q!=="string")return null;const scopable=n.nodeType===Node.ELEMENT_NODE&&!q.trimStart().startsWith(":scope");try{return n.querySelector(scopable?":scope "+q:q);}catch{return null;}});',
                    'oD("queryAll",(n,q)=>{if(!n?.querySelectorAll||typeof q!=="string")return [];const scopable=n.nodeType===Node.ELEMENT_NODE&&!q.trimStart().startsWith(":scope");try{return [...n.querySelectorAll(scopable?":scope "+q:q)];}catch{return [];}});',
                    'oD("storeGet",window.$tfs.get);',
                    'oD("storeSet",window.$tfs.set);',
                    'return Object.freeze(obj);})());',
                    /* Name shim */
                    'def("__name",(fn,n)=>{try{Object.defineProperty(fn,"name",{value:n,configurable:true});}catch{}return fn;});',
                    /* Hydration marker */
                    'def("$tfhydra",!0);})();',
                ].join(''),
            );
        });
    });

    describe('ARC_GLOBAL', () => {
        it('Should be minified correct', () => {
            expect(ARC_GLOBAL).toBe(
                [
                    '(function(w){',
                    'if(!w.$tfarc){',
                    'const f=new Map(),d=new Map(),v=new Map();',
                    'Object.defineProperty(w,"$tfarc",{value:Object.freeze({',
                    /* Release */
                    'release(uid){',
                    'const r=v.get(uid);',
                    'if(!r)return;',
                    'v.delete(uid);',
                    'const fe=f.get(r.fn_id);',
                    'if(fe&&--fe.refs<=0)f.delete(r.fn_id);',
                    'const de=d.get(r.data_id);',
                    'if(de&&--de.refs<=0)d.delete(r.data_id);',
                    '},',
                    /* Spark */
                    'spark(FNS,DAT){',
                    'const ATOMIC=!!w.$tfhydra;',
                    'for(const[DID,val]of DAT){',
                    'if(!d.has(DID))d.set(DID,{val,refs:0});',
                    '}',
                    'for(const[FID,fn]of FNS){',
                    'if(!f.has(FID))f.set(FID,{fn,refs:0});',
                    'const nodes=document.querySelectorAll(`[data-tfhf="${FID}"]`);',
                    'for(const n of nodes){',
                    'const DID=n.getAttribute("data-tfhd")||undefined;',
                    'const DREG=DID?d.get(DID):{};',
                    'const FREG=f.get(FID);',
                    'const UID=Math.random().toString(36).slice(2);',
                    'Object.defineProperty(n,"$uid",{value:UID,configurable:false,writable:false});',
                    'if(ATOMIC&&!n.$tfVM){',
                    'Object.defineProperties(n,{',
                    '$subscribe:{value:(msg,fn)=>w.$tfr.subscribe(n.$uid,msg,fn),configurable:!1,writable:!1},',
                    '$unsubscribe:{value:msg=>w.$tfr.unsubscribe(n.$uid,msg),configurable:!1,writable:!1},',
                    '$publish:{value:(msg,data)=>w.$tfr.publish(msg,data),configurable:!1,writable:!1},',
                    '$tfVM:{get:()=>!0,configurable:!1}',
                    '});',
                    '}',
                    'try{',
                    'FREG?.fn?.(',
                    'ATOMIC',
                    '?{el:n,data:w.$tfdr(n,DREG?.val??{}),$:w.$tfutils}',
                    ':{el:n,data:DREG?.val??{}}',
                    ');',
                    'v.set(UID,{fn_id:FID,data_id:DID});',
                    'if(FREG)FREG.refs++;',
                    'if(DID&&DREG)DREG.refs++;',
                    'if(ATOMIC&&typeof n.$mount==="function"){',
                    'try{n.$mount()}catch{}',
                    '}',
                    '}catch{}}}},}),configurable:!1,writable:!1});}})(window);',
                ].join(''),
            );
        });
    });

    describe('ARC_GLOBAL_OBSERVER', () => {
        it('Should be minified correct', () => {
            expect(ARC_GLOBAL_OBSERVER).toBe(
                [
                    '(function(){',
                    'const c=n=>{',
                    'if(n&&n.$uid)window.$tfarc?.release(n.$uid);',
                    'if(n.children?.length){for(let i=0;i<n.children.length;i++)c(n.children[i]);}',
                    '};',
                    'const o=new MutationObserver(e=>{',
                    'for(let i=0;i<e.length;i++){',
                    'for(let y=0;y<e[i].removedNodes.length;y++){',
                    'c(e[i].removedNodes[y]);',
                    '}}});',
                    'o.observe(document.body,{childList:!0,subtree:!0});return o;})();',
                ].join(''),
            );
        });
    });
});
